apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YmxhaGJsYWg=
  mongo-root-password: YmxhaGJsYWg=
##base64 tipinde girilmeli  bash -n 'username' | base64